name: test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      - name: install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm test
